import type { SkeletonTemplate } from './SkeletonTemplate'

export const humanoidTemplate: SkeletonTemplate = {
  id: 'humanoid',
  name: 'Humanoid',
  type: 'humanoid',
  bones: [
    { name: 'Hips', parent: null, defaultLocalPosition: [0, 1.0, 0], landmarkKey: 'hips' },
    { name: 'Spine', parent: 'Hips', defaultLocalPosition: [0, 0.12, 0] },
    { name: 'Spine1', parent: 'Spine', defaultLocalPosition: [0, 0.12, 0] },
    { name: 'Spine2', parent: 'Spine1', defaultLocalPosition: [0, 0.12, 0] },
    { name: 'Neck', parent: 'Spine2', defaultLocalPosition: [0, 0.15, 0] },
    { name: 'Head', parent: 'Neck', defaultLocalPosition: [0, 0.1, 0], landmarkKey: 'headTop' },
    // Left arm
    { name: 'LeftShoulder', parent: 'Spine2', defaultLocalPosition: [0.05, 0.12, 0], landmarkKey: 'leftShoulder' },
    { name: 'LeftUpperArm', parent: 'LeftShoulder', defaultLocalPosition: [0.12, 0, 0] },
    { name: 'LeftLowerArm', parent: 'LeftUpperArm', defaultLocalPosition: [0.25, 0, 0], landmarkKey: 'leftElbow' },
    { name: 'LeftHand', parent: 'LeftLowerArm', defaultLocalPosition: [0.25, 0, 0], landmarkKey: 'leftWrist' },
    // Left fingers
    { name: 'LeftThumb1', parent: 'LeftHand', defaultLocalPosition: [0.03, 0, 0.02] },
    { name: 'LeftThumb2', parent: 'LeftThumb1', defaultLocalPosition: [0.02, 0, 0.01] },
    { name: 'LeftThumb3', parent: 'LeftThumb2', defaultLocalPosition: [0.02, 0, 0] },
    { name: 'LeftIndex1', parent: 'LeftHand', defaultLocalPosition: [0.06, 0, 0.02] },
    { name: 'LeftIndex2', parent: 'LeftIndex1', defaultLocalPosition: [0.03, 0, 0] },
    { name: 'LeftIndex3', parent: 'LeftIndex2', defaultLocalPosition: [0.02, 0, 0] },
    { name: 'LeftMiddle1', parent: 'LeftHand', defaultLocalPosition: [0.06, 0, 0] },
    { name: 'LeftMiddle2', parent: 'LeftMiddle1', defaultLocalPosition: [0.03, 0, 0] },
    { name: 'LeftMiddle3', parent: 'LeftMiddle2', defaultLocalPosition: [0.02, 0, 0] },
    { name: 'LeftRing1', parent: 'LeftHand', defaultLocalPosition: [0.06, 0, -0.02] },
    { name: 'LeftRing2', parent: 'LeftRing1', defaultLocalPosition: [0.03, 0, 0] },
    { name: 'LeftRing3', parent: 'LeftRing2', defaultLocalPosition: [0.02, 0, 0] },
    { name: 'LeftPinky1', parent: 'LeftHand', defaultLocalPosition: [0.05, 0, -0.04] },
    { name: 'LeftPinky2', parent: 'LeftPinky1', defaultLocalPosition: [0.02, 0, 0] },
    { name: 'LeftPinky3', parent: 'LeftPinky2', defaultLocalPosition: [0.02, 0, 0] },
    // Right arm (mirrored)
    { name: 'RightShoulder', parent: 'Spine2', defaultLocalPosition: [-0.05, 0.12, 0], landmarkKey: 'rightShoulder' },
    { name: 'RightUpperArm', parent: 'RightShoulder', defaultLocalPosition: [-0.12, 0, 0] },
    { name: 'RightLowerArm', parent: 'RightUpperArm', defaultLocalPosition: [-0.25, 0, 0], landmarkKey: 'rightElbow' },
    { name: 'RightHand', parent: 'RightLowerArm', defaultLocalPosition: [-0.25, 0, 0], landmarkKey: 'rightWrist' },
    // Right fingers
    { name: 'RightThumb1', parent: 'RightHand', defaultLocalPosition: [-0.03, 0, 0.02] },
    { name: 'RightThumb2', parent: 'RightThumb1', defaultLocalPosition: [-0.02, 0, 0.01] },
    { name: 'RightThumb3', parent: 'RightThumb2', defaultLocalPosition: [-0.02, 0, 0] },
    { name: 'RightIndex1', parent: 'RightHand', defaultLocalPosition: [-0.06, 0, 0.02] },
    { name: 'RightIndex2', parent: 'RightIndex1', defaultLocalPosition: [-0.03, 0, 0] },
    { name: 'RightIndex3', parent: 'RightIndex2', defaultLocalPosition: [-0.02, 0, 0] },
    { name: 'RightMiddle1', parent: 'RightHand', defaultLocalPosition: [-0.06, 0, 0] },
    { name: 'RightMiddle2', parent: 'RightMiddle1', defaultLocalPosition: [-0.03, 0, 0] },
    { name: 'RightMiddle3', parent: 'RightMiddle2', defaultLocalPosition: [-0.02, 0, 0] },
    { name: 'RightRing1', parent: 'RightHand', defaultLocalPosition: [-0.06, 0, -0.02] },
    { name: 'RightRing2', parent: 'RightRing1', defaultLocalPosition: [-0.03, 0, 0] },
    { name: 'RightRing3', parent: 'RightRing2', defaultLocalPosition: [-0.02, 0, 0] },
    { name: 'RightPinky1', parent: 'RightHand', defaultLocalPosition: [-0.05, 0, -0.04] },
    { name: 'RightPinky2', parent: 'RightPinky1', defaultLocalPosition: [-0.02, 0, 0] },
    { name: 'RightPinky3', parent: 'RightPinky2', defaultLocalPosition: [-0.02, 0, 0] },
    // Left leg
    { name: 'LeftUpperLeg', parent: 'Hips', defaultLocalPosition: [0.1, -0.05, 0] },
    { name: 'LeftLowerLeg', parent: 'LeftUpperLeg', defaultLocalPosition: [0, -0.42, 0], landmarkKey: 'leftKnee' },
    { name: 'LeftFoot', parent: 'LeftLowerLeg', defaultLocalPosition: [0, -0.4, 0], landmarkKey: 'leftAnkle' },
    { name: 'LeftToes', parent: 'LeftFoot', defaultLocalPosition: [0, -0.05, 0.1] },
    // Right leg (mirrored)
    { name: 'RightUpperLeg', parent: 'Hips', defaultLocalPosition: [-0.1, -0.05, 0] },
    { name: 'RightLowerLeg', parent: 'RightUpperLeg', defaultLocalPosition: [0, -0.42, 0], landmarkKey: 'rightKnee' },
    { name: 'RightFoot', parent: 'RightLowerLeg', defaultLocalPosition: [0, -0.4, 0], landmarkKey: 'rightAnkle' },
    { name: 'RightToes', parent: 'RightFoot', defaultLocalPosition: [0, -0.05, 0.1] },
  ],
  requiredLandmarks: [
    { key: 'headTop', label: 'Head Top', description: 'Top of the head', color: '#ff4444' },
    { key: 'chin', label: 'Chin', description: 'Bottom of the chin', color: '#ff6644' },
    { key: 'leftShoulder', label: 'Left Shoulder', description: 'Left shoulder joint', color: '#44ff44' },
    { key: 'rightShoulder', label: 'Right Shoulder', description: 'Right shoulder joint', color: '#44ff44' },
    { key: 'leftElbow', label: 'Left Elbow', description: 'Left elbow joint', color: '#44aaff' },
    { key: 'rightElbow', label: 'Right Elbow', description: 'Right elbow joint', color: '#44aaff' },
    { key: 'leftWrist', label: 'Left Wrist', description: 'Left wrist joint', color: '#aa44ff' },
    { key: 'rightWrist', label: 'Right Wrist', description: 'Right wrist joint', color: '#aa44ff' },
    { key: 'hips', label: 'Hips', description: 'Center of the hip area', color: '#ffaa44' },
    { key: 'leftKnee', label: 'Left Knee', description: 'Left knee joint', color: '#44ffaa' },
    { key: 'rightKnee', label: 'Right Knee', description: 'Right knee joint', color: '#44ffaa' },
    { key: 'leftAnkle', label: 'Left Ankle', description: 'Left ankle joint', color: '#ff44aa' },
    { key: 'rightAnkle', label: 'Right Ankle', description: 'Right ankle joint', color: '#ff44aa' },
  ],
  optionalLandmarks: [
    { key: 'leftFingertips', label: 'Left Fingertips', description: 'Tips of left fingers', color: '#aaaaff' },
    { key: 'rightFingertips', label: 'Right Fingertips', description: 'Tips of right fingers', color: '#aaaaff' },
    { key: 'leftToes', label: 'Left Toes', description: 'Tips of left toes', color: '#aaffaa' },
    { key: 'rightToes', label: 'Right Toes', description: 'Tips of right toes', color: '#aaffaa' },
  ],
  testAnimations: ['tpose', 'wave', 'walkCycle', 'bendTest'],
}
